# Generated by Django 3.0.3 on 2020-02-15 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imgurl',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
